BEGIN TRANSACTION;
DROP TABLE IF EXISTS "TB_RESULTADO";
CREATE TABLE IF NOT EXISTS "TB_RESULTADO" (
	"ID_PROVA"	INTEGER,
	"ID_PILOTO"	INTEGER,
	"NR_TEMPO_PROVA"	NUMERIC,
	"NR_COLOC_FINAL"	INTEGER,
	"NR_POSICAO_GRID3"	INTEGER,
	"NR_MELHOR_VOLTA"	INTEGER,
	FOREIGN KEY("ID_PILOTO") REFERENCES "TB_PILOTO"("ID_PILOTO"),
	FOREIGN KEY("ID_PROVA") REFERENCES "TB_PROVA"("ID_PROVA")
);
DROP TABLE IF EXISTS "TB_PROVA";
CREATE TABLE IF NOT EXISTS "TB_PROVA" (
	"ID_PROVA"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"DT_PROVA"	TEXT,
	"NM_SITUACAO"	TEXT,
	"ID_CIRCUITO"	INTEGER,
	FOREIGN KEY("ID_CIRCUITO") REFERENCES "TB_CIRCUITO"("ID_CIRCUITO")
);
DROP TABLE IF EXISTS "TB_PILOTO";
CREATE TABLE IF NOT EXISTS "TB_PILOTO" (
	"ID_PILOTO"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"NM_PILOTO"	TEXT,
	"DT-NASCIMENTO"	TEXT,
	"ID_PAIS"	INTEGER,
	"ID_EQUIPE"	INTEGER,
	FOREIGN KEY("ID_PAIS") REFERENCES "TB_PAIS"("ID_PAIS"),
	FOREIGN KEY("ID_EQUIPE") REFERENCES "TB_EQUIPE"("ID_EQUIPE")
);
DROP TABLE IF EXISTS "TB_EQUIPE";
CREATE TABLE IF NOT EXISTS "TB_EQUIPE" (
	"ID_EQUIPE"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"NM_EQUIPE"	TEXT,
	"ID_PAIS"	INTEGER,
	FOREIGN KEY("ID_PAIS") REFERENCES "TB_PAIS"("ID_PAIS")
);
DROP TABLE IF EXISTS "TB_CIRCUITO";
CREATE TABLE IF NOT EXISTS "TB_CIRCUITO" (
	"ID_CIRCUITO"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"NM_CIRCUITO"	TEXT,
	"NR_EXTENSAO"	INTEGER,
	"ID_PAIS"	INTEGER,
	FOREIGN KEY("ID_PAIS") REFERENCES "TB_PAIS"("ID_PAIS")
);
DROP TABLE IF EXISTS "TB_PAIS";
CREATE TABLE IF NOT EXISTS "TB_PAIS" (
	"ID_PAIS"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"NM_PAIS"	TEXT NOT NULL,
	"NR_POPULACAO"	INTEGER NOT NULL
);
